[versions]
agp = "8.11.2"
browser = "1.9.0"
androidbrowserhelper = "2.5.0"
browserVersion = "1.7.0"
coreSplashscreen = "1.2.0"
credentials = "1.3.0"
credentialsPlayServicesAuth = "1.5.0"
credentialsPlayServicesAuthVersion = "1.3.0"
firebaseBom = "34.9.0"
coreKtx = "1.17.0"
googleid = "1.2.0"
googleidVersion = "1.1.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.6.1"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesAndroidVersion = "1.7.3"
lifecycleRuntimeKtx = "2.10.0"
lifecycleRuntimeKtxVersion = "2.6.2"
material = "1.10.0"
materialVersion = "1.11.0"
okhttp = "5.3.2"
playServicesAuth = "21.5.0"
workRuntimeKtx = "2.11.1"

[libraries]
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }

androidbrowserhelper = { group = "com.google.androidbrowserhelper", name = "androidbrowserhelper", version.ref = "androidbrowserhelper" }

androidx-browser-v170 = { module = "androidx.browser:browser", version.ref = "browserVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentialsPlayServicesAuth" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
androidx-credentials-play-services-auth-v130 = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuthVersion" }
androidx-credentials-v130 = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx-v262 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
googleid-v110 = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleidVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-android-v173 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroidVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }